version: "3.8"
services:
  hogrider_db:
    image: arm64v8/postgres
    container_name: hogrider_db
    env_file:
      - packages/config/HogRiderSecrets/db.env
    volumes:
      - hogrider_volume:/var/lib/postgresql/data/
    ports:
      - 5444:5432
    networks:
      - hogrider_network
    restart: always

  hogrider:
    container_name: hogrider
    image: hogrider:v1.0
    depends_on:
      - hogrider_db
    build:
      context: .
      dockerfile: hogrider.dockerfile
    env_file:
      - packages/config/HogRiderSecrets/db.env
    volumes:
      - .:/opt/code
    networks:
      - hogrider_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

volumes:
  hogrider_volume:
    external: true
    name: hogrider_volume

networks:
  hogrider_network:
    external: true
    name: hogrider_network

